version: '3.8'
services:
  postgres:
    image: timescale/timescaledb-ha:pg15-latest
    environment:
      POSTGRES_DB: ai_app_db
      POSTGRES_USER: ai_user
      POSTGRES_PASSWORD: ai_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      postgres -c 'shared_preload_libraries=pgvector'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ai_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
